DROP TABLE TB_RECEBER_REC;

CREATE TABLE TB_RECEBER_REC (
    COD_PAGTO        VARCHAR(40)     NOT NULL,
    COD_EMP          INTEGER         NOT NULL,
    COD_CLIENTE      INTEGER         NOT NULL,
    NUM_FAT          INTEGER         NOT NULL,
    NUM_PARC         INTEGER         NOT NULL,
    DATA_REC         TIMESTAMP,
    VLR_RECEBIDO     NUMERIC(16, 2),
    USU_REC          INTEGER,
    SIT_CONTROLE     VARCHAR(1),
    CONSTRAINT TB_RECEBER_REC_PK PRIMARY KEY (COD_PAGTO, COD_EMP, COD_CLIENTE, NUM_FAT, NUM_PARC)
);