[GERAL]
#TP_AMBIENTE=PROD
TP_AMBIENTE=TEST
#TP_AMBIENTE=COPIA
IN_ARGLOG=True
IN_MEMLOG=True
IN_DEBUG=True
IN_ERRO=True
IN_INFO=True
IN_SERIAL=False
IN_ACESSO=False

[LICENCA]
QT_ACESSO=515444452332

[TIMER]
#900000 - 15 minutos
NR_ENVIO=900000
#60000 - 1 minuto
NR_RECEB=60000

[DADOS_PROD]
DS_DATABASE_CLI=C:\Projetos\SGLoja\Sistema\Dados\CLI_DADOS.FDB
DS_USERNAME_CLI=SYSDBA
DS_PASSWORD_CLI=key2624

DS_DATABASE_FB=C:\FVendas\Bin\Dados\FB_DADOS.FDB
DS_USERNAME_FB=SYSDBA
DS_PASSWORD_FB=key2624

[DADOS_TEST]
DS_DATABASE_CLI={appPath}\Dados\CLI_DADOS.FDB
DS_USERNAME_CLI=SYSDBA
DS_PASSWORD_CLI=masterkey

DS_DATABASE_FB={appPath}\Dados\FB_DADOS.FDB
DS_USERNAME_FB=SYSDBA
DS_PASSWORD_FB=masterkey

[DADOS_COPIA]
DS_DATABASE_CLI=C:\Projetos\Delphi\camargo\FVENDAS\DadosCopia\CLI_DADOS_COPIA.FDB
DS_USERNAME_CLI=SYSDBA
DS_PASSWORD_CLI=masterkey

DS_DATABASE_FB=C:\Projetos\Delphi\camargo\FVENDAS\DadosCopia\FB_DADOS_COPIA.FDB
DS_USERNAME_FB=SYSDBA
DS_PASSWORD_FB=masterkey