DROP TABLE TB_RECEBER_PAG;

CREATE TABLE TB_RECEBER_PAG (
    COD_PAGTO    VARCHAR(40) NOT NULL,
    NRO_PAGTO    INTEGER NOT NULL,
    TIP_DOCTO    INTEGER NOT NULL,
    NRO_DOCTO    INTEGER,
    VLR_DOCTO    NUMERIC(15,2) NOT NULL,
    DAT_DOCTO    DATE,
    COD_MOEDA    INTEGER,
    NRO_BANCO    INTEGER,
    COD_EMPRESA  INTEGER,
    NRO_CONTA    VARCHAR(10),
    CONSTRAINT TB_RECEBER_PAG_PK PRIMARY KEY (COD_PAGTO, NRO_PAGTO)
);