create or alter view V_CAD_CLIENTE_FV
select 
  a.CODCLIENTE        
, a.NOME              
, a.RAZAOSOCIAL       
, a.TIPOCADASTRO      
, a.TIPOCLIENTE       
, a.TIPOFISCAL        
, a.SEXO              
, a.ESTADOCIVIL       
, a.DATANASCFUND      
, a.INATIVO           
, a.CODREGVEN         
, a.CODVEND           
, a.ATACVAR           
, a.ENDERTPLOGRAD     
, a.ENDERLOGRAD       
, a.ENDERNUMLOGRAD    
, a.ENDERCOMPLEMENTO  
, a.ENDERBAIRRO       
, a.CODCIDADE         
, a.DOCFISCAL         
, a.DOCFISCAL2        
, a.DOCIDENTIDADE     
, a.TIPOTELEFONE1     
, a.TIPOTELEFONE2     
, a.TIPOTELEFONE3     
, a.NUMTELEFONE1      
, a.NUMTELEFONE2      
, a.NUMTELEFONE3      
, a.PESSOACONTATO     
, a.EMAIL1            
, a.EMAIL2            
, a.NOMEPAI           
, a.NOMEMAE           
, a.NOMECONJUGE       
, a.NACIONALIDADE     
, a.FOTO              
, a.OBS               
, a.PROFISSAO         
, a.NOMEEMPPROF       
, a.NUMTELEFONEEMP    
, a.TEMPOEMP          
, a.GRAUESC           
, a.CODTIPOCLIENTE    
, a.USUINC            
, a.DATAINC           
, a.CODEMPINC         
, a.USUARIO           
, a.DATAATU           
, a.HORAATU           
, a.MOEDACOMPRA       
, a.DOCTINBRADO       
, a.PRJUROS           
, a.DSLOCAL           
, a.TIPOVLVENDA       
, a.VLMAXCREDITO      
from CAD_CLIENTE a
;